version: '2'
services:
    accessmux-app:
        image: accessmux
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://accessmux-mariadb:3306/accessmux
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    accessmux-mariadb:
        extends:
            file: mariadb.yml
            service: accessmux-mariadb
