---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: accessmux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accessmux
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: "registry.gitlab.com/kuba2915/accessmux:master"
          imagePullPolicy: Always
          name: accessmux-container
          livenessProbe:
            httpGet:
              path: /
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: accessmux-service
spec:
  ports:
     -  name: http
        port: 80
        protocol: TCP
  selector:
    app: accessmux
  type: NodePort
